### ISSUE TITLE
Push a release/snapshot to Clojars

### ISSUE THREAD

**Issue by r0man** [alumbra/alumbra.web#1]
Hi @xsc,

I was using the graphiql handler in alumbra < 2.x. I haven't found where it moved yet, but would much rather prefer to use one of the frontends included here. Could you push a release/snaphsot of this repo to Clojars?

Thanks, Roman

**Comment by xsc** [comment]
I pushed a SNAPSHOT (0.1.0-SNAPSHOT) and the auto-generated documentation (https://alumbra.github.io/alumbra.web/). I'll release a stable version after I wrote a reasonable README. :)

**Comment by r0man** [comment]
@xsc Thanks again! :)
